"""
Streamlit demo UI for the Support Assistant. Run:  streamlit run app.py
(run `python train.py` first if you haven't — it needs the trained model + index)
"""
import streamlit as st
from src.pipeline import SupportAssistant

st.set_page_config(page_title="AI Support Assistant", page_icon="\U0001F4AC", layout="centered")


@st.cache_resource
def get_assistant():
    return SupportAssistant()


st.title("AI Customer Support Assistant")
st.caption(
    "RAG pipeline: intent classification (TF-IDF + Logistic Regression) → "
    "sentiment scoring (VADER) → knowledge-base retrieval (LSA embeddings + FAISS) → "
    "answer generation."
)

try:
    assistant = get_assistant()
except FileNotFoundError:
    st.error("Model files not found. Run `python train.py` from the project root first, then reload this page.")
    st.stop()

with st.sidebar:
    st.header("About")
    st.write(
        "This demo classifies a support ticket's intent and sentiment, retrieves "
        "the most relevant knowledge-base article, and drafts a reply."
    )
    st.write("**Try:**")
    st.code("I was charged twice and no one has refunded me!")
    st.code("How long does shipping usually take?")
    st.code("The app crashes every time I open it")
    st.divider()
    st.write(
        "Set an `OPENAI_API_KEY` environment variable before launching to switch "
        "the generation step from template mode to live LLM mode."
    )

query = st.text_area("Customer message", placeholder="Type a support request here...", height=100)

if st.button("Get response", type="primary") and query.strip():
    with st.spinner("Processing..."):
        result = assistant.handle(query)

    col1, col2 = st.columns(2)
    with col1:
        st.metric("Detected intent", result["intent"]["intent"], f"{result['intent']['confidence']:.0%} confidence")
    with col2:
        st.metric("Detected sentiment", result["sentiment"]["label"], f"{result['sentiment']['compound']:+.2f}")

    st.subheader("Suggested reply")
    st.info(result["answer"])
    st.caption(f"Generated by: {result['generation_backend']}")

    with st.expander("Retrieved knowledge-base articles (what the answer is grounded in)"):
        for r in result["retrieved"]:
            st.markdown(f"**{r['question']}**  \n_similarity: {r['similarity']}_  \n{r['answer']}")

    with st.expander("Full intent probability breakdown"):
        st.json(result["intent"]["all_scores"])
